/**
 * A locally-stored voice recording.
 *
 * Phase 3 keeps these on-device only. Phase 4 adds a transcript
 * generated by the `transcribe` Edge Function (OpenAI Whisper).
 * In a later phase each recording becomes a `notes` row
 * (audio_path + body_raw = transcript).
 */
export type TranscriptStatus = 'none' | 'processing' | 'ready' | 'failed';
export type CleanupStatus = 'none' | 'processing' | 'ready' | 'failed';

export interface Recording {
  id: string;
  uri: string; // file:// path in the app's document directory (local-only)
  durationMillis: number;
  createdAt: string; // ISO timestamp
  updatedAt?: string; // ISO; used for last-write-wins sync

  // Phase 6 — the book this entry belongs to (undefined = unassigned)
  bookId?: string;

  // Phase 8 — goals this entry was AI-linked to
  goalIds?: string[];

  // Phase 4 — speech-to-text
  transcript?: string;
  transcriptStatus: TranscriptStatus;
  transcriptError?: string;

  // Phase 5 — AI cleanup (the structured page)
  title?: string;
  bodyClean?: string;
  cleanupStatus: CleanupStatus;
  cleanupError?: string;
}
